### PR TITLE
Send a voice and get voice answer

### PR DESCRIPTION
**Pull request by hdcola**

### CODE REVIEW

**Comment by scmanjarrez** [comment]
Wow, nice one. I think we can use the language returned from EdgeGPT response to use as output language. I remember some tag showing the current prompt language.

**Comment by hdcola** [comment]
Yes, I saw the message information.

In this PR, I put logger message in it.

Maybe help user look the message information.

**Comment by hdcola** [comment]
My code is not good. But the features are my favourite. You can use it to improve your language skills that include speaking, reading, listening.

**Comment by scmanjarrez** [comment]
I've been testing this feature, but it doesn't seem to work when bold text or italic is included. We can try to polish it before merging to master. Also, we should mention in the README that not all voices are available, some are only available in certain regions (i.e. spanish, I was trying a voice that wasn't on my region and it was raising an exception)

**Comment by hdcola** [comment]
Yes, I will fix the re bug.

**Comment by hdcola** [comment]
Ok, now the voice have bold vocabulary

**Comment by hdcola** [comment]
Now, I make /voice simpler to change your favourite voice. It is my favourite. Because changing your voice will often make it more fun to practice and familiarize you with the different sounds.

**Comment by scmanjarrez** [comment]
I can merge it to another branch. I need to change few things before merging into master, I'll change the current allowed users system to store it in a sqlite database and have more control in the voice used by every user/chat_id

**Comment by scmanjarrez** [comment]
I merged this PR into voice_dev. I'll have little time to work on it the following days but I'll try to prepare the merge with master by the sunday.

**Pull request closed without merging**
